server:
  port: 17500
  
spring:
  mvc:
    favicon:
      enabled: false
  jmx:
    enabled: false
  cache:
    type: simple
logging:
  level:
    org.springframework.web: INFO
  pattern:
    console: "%d{yyyy-MM-dd'T'HH:mm:ss,SSSXXX, UTC} [%thread] %-5level %logger{36} - %msg%n"
qrcode:
  service:
    dimension: 640
  cache:
    maxAgeMinutes: 30
